# Generated by Django 2.2.4 on 2019-09-01 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
    ]
